namespace Mango.Compiler.Syntax
{
    public enum SyntaxKind
    {
        None,

        #region ...

        ExclamationToken,
        DoubleQuoteToken,
        HashToken,
        DollarToken,
        PercentToken,
        AmpersandToken,
        SingleQuoteToken,
        OpenParenToken,
        CloseParenToken,
        AsteriskToken,
        PlusToken,
        CommaToken,
        MinusToken,
        DotToken,
        SlashToken,
        ColonToken,
        SemicolonToken,
        LessThanToken,
        EqualsToken,
        GreaterThanToken,
        QuestionToken,
        AtToken,
        OpenBracketToken,
        BackslashToken,
        CloseBracketToken,
        CaretToken,
        UnderscoreToken,
        BacktickToken,
        OpenBraceToken,
        BarToken,
        CloseBraceToken,
        TildeToken,

        BoolKeyword,
        I8Keyword,
        U8Keyword,
        I16Keyword,
        U16Keyword,
        I32Keyword,
        U32Keyword,
        I64Keyword,
        U64Keyword,
        F32Keyword,
        F64Keyword,
        VoidKeyword,

        ModuleKeyword,
        TypeKeyword,
        FieldKeyword,
        DeclareKeyword,
        DefineKeyword,
        LocalKeyword,
        GlobalKeyword,

        LdnullKeyword,
        LdcKeyword,
        LdftnKeyword,
        LdindKeyword,
        LdfldKeyword,
        LdelemKeyword,
        LdlocKeyword,
        LdargKeyword,
        LdfldaKeyword,
        LdelemaKeyword,
        LdlocaKeyword,
        LdargaKeyword,
        StindKeyword,
        StfldKeyword,
        StelemKeyword,
        StlocKeyword,
        StargKeyword,
        SyscallKeyword,
        CallKeyword,
        CalliKeyword,
        RetKeyword,

        BreakKeyword,
        DupKeyword,
        NopKeyword,
        PopKeyword,

        AddKeyword,
        AndKeyword,
        DivKeyword,
        DivUnKeyword,
        MulKeyword,
        OrKeyword,
        RemKeyword,
        RemUnKeyword,
        ShlKeyword,
        ShrKeyword,
        ShrUnKeyword,
        SubKeyword,
        XorKeyword,

        NegKeyword,
        NotKeyword,

        ConvKeyword,
        ConvUnKeyword,

        CeqKeyword,
        CgtKeyword,
        CgtUnKeyword,
        CltKeyword,
        CltUnKeyword,

        BeqKeyword,
        BgeKeyword,
        BgeUnKeyword,
        BgtKeyword,
        BgtUnKeyword,
        BleKeyword,
        BleUnKeyword,
        BltKeyword,
        BltUnKeyword,
        BneUnKeyword,
        BrKeyword,
        BrfalseKeyword,
        BrtrueKeyword,

        BeqSKeyword,
        BgeSKeyword,
        BgeUnSKeyword,
        BgtSKeyword,
        BgtUnSKeyword,
        BleSKeyword,
        BleUnSKeyword,
        BltSKeyword,
        BltUnSKeyword,
        BneUnSKeyword,
        BrSKeyword,
        BrfalseSKeyword,
        BrtrueSKeyword,

        LdobjKeyword,
        StobjKeyword,
        CpobjKeyword,
        InitobjKeyword,
        LdlenKeyword,
        NewarrKeyword,
        NewobjKeyword,



        EndOfFileToken,

        BadToken,

        IdentifierToken,
        StringLiteralToken,
        CharacterLiteralToken,
        I32LiteralToken,







        #endregion




        #region Type Expressions

        ArrayType,
        BoolType,
        Float32Type,
        Float64Type,
        FunctionType,
        Int16Type,
        Int32Type,
        Int64Type,
        Int8Type,
        StructuredType,
        ReferenceType,
        SpanType,
        UInt16Type,
        UInt32Type,
        UInt64Type,
        UInt8Type,
        VoidType,

        #endregion

        #region Declarations

        CompilationUnit,
        ModuleDeclaration,
        TypeDeclaration,
        FieldDeclaration,
        FunctionDeclaration,
        ParameterDeclaration,
        FunctionBody,
        LocalDeclaration,

        #endregion

        #region Instructions

        LabeledInstruction,

        Ldnull,
        Ldc,
        Ldftn,
        Ldind,
        Ldfld,
        Ldelem,
        Ldloc,
        Ldarg,
        Ldflda,
        Ldelema,
        Ldloca,
        Ldarga,
        Stind,
        Stfld,
        Stelem,
        Stloc,
        Starg,
        Syscall,
        Call,
        Calli,
        Ret,

        Break,
        Dup,
        Nop,
        Pop,

        Add,
        And,
        Div,
        Div_Un,
        Mul,
        Or,
        Rem,
        Rem_Un,
        Shl,
        Shr,
        Shr_Un,
        Sub,
        Xor,

        Neg,
        Not,

        Conv,
        Conv_Un,

        Ceq,
        Cgt,
        Cgt_Un,
        Clt,
        Clt_Un,

        Beq,
        Bge,
        Bge_Un,
        Bgt,
        Bgt_Un,
        Ble,
        Ble_Un,
        Blt,
        Blt_Un,
        Bne_Un,
        Br,
        Brfalse,
        Brtrue,

        Beq_S,
        Bge_S,
        Bge_Un_S,
        Bgt_S,
        Bgt_Un_S,
        Ble_S,
        Ble_Un_S,
        Blt_S,
        Blt_Un_S,
        Bne_Un_S,
        Br_S,
        Brfalse_S,
        Brtrue_S,

        Ldobj,
        Stobj,
        Cpobj,
        Initobj,
        Ldlen,
        Newarr,
        Newobj,

        #endregion
    }

    //internal enum SyntaxKind
    //{
    //    None,

    //    ExclamationToken,
    //    DoubleQuoteToken,
    //    HashToken,
    //    DollarToken,
    //    PercentToken,
    //    AmpersandToken,
    //    SingleQuoteToken,
    //    OpenParenToken,
    //    CloseParenToken,
    //    AsteriskToken,
    //    PlusToken,
    //    CommaToken,
    //    MinusToken,
    //    DotToken,
    //    SlashToken,
    //    ColonToken,
    //    SemicolonToken,
    //    LessThanToken,
    //    EqualsToken,
    //    GreaterThanToken,
    //    QuestionToken,
    //    AtToken,
    //    OpenBracketToken,
    //    BackslashToken,
    //    CloseBracketToken,
    //    CaretToken,
    //    UnderscoreToken,
    //    BacktickToken,
    //    OpenBraceToken,
    //    BarToken,
    //    CloseBraceToken,
    //    TildeToken,

    //    I8Keyword,
    //    I16Keyword,
    //    I32Keyword,
    //    I64Keyword,
    //    U8Keyword,
    //    U16Keyword,
    //    U32Keyword,
    //    U64Keyword,
    //    F32Keyword,
    //    F64Keyword,
    //    VoidKeyword,

    //    DeclareKeyword,
    //    DefineKeyword,
    //    GlobalKeyword,
    //    LocalKeyword,
    //    ModuleKeyword,
    //    TypeKeyword,
    //    UsesKeyword,

    //    PrivateKeyword,
    //    InternalKeyword,
    //    PublicKeyword,

    //    InternalsVisibleToKeyword,

    //    SecurityTransparentKeyword,
    //    SecuritySafeCriticalKeyword,
    //    SecurityCriticalKeyword,

    //    EntryPointKeyword,
    //    MaxStackKeyword,
    //    SyscallKeyword,

    //    AddInstruction,
    //    AndInstruction,
    //    BreakInstruction,
    //    CeqInstruction,
    //    CeqUnInstruction,
    //    CgeInstruction,
    //    CgeUnInstruction,
    //    CgtInstruction,
    //    CgtUnInstruction,
    //    CleInstruction,
    //    CleUnInstruction,
    //    CltInstruction,
    //    CltUnInstruction,
    //    CneInstruction,
    //    CneUnInstruction,
    //    ConvF32Instruction,
    //    ConvF32UnInstruction,
    //    ConvF64Instruction,
    //    ConvF64UnInstruction,
    //    ConvI8Instruction,
    //    ConvI16Instruction,
    //    ConvI32Instruction,
    //    ConvI64Instruction,
    //    ConvU8Instruction,
    //    ConvU16Instruction,
    //    ConvU32Instruction,
    //    ConvU64Instruction,
    //    DivInstruction,
    //    DivUnInstruction,
    //    DupInstruction,
    //    Dup2Instruction,
    //    Ldarg0Instruction,
    //    Ldarg1Instruction,
    //    Ldarg2Instruction,
    //    Ldarg3Instruction,
    //    LdelemInstruction,
    //    LdelemaInstruction,
    //    LdlenInstruction,
    //    Ldloc0Instruction,
    //    Ldloc1Instruction,
    //    Ldloc2Instruction,
    //    Ldloc3Instruction,
    //    MulInstruction,
    //    NegInstruction,
    //    NipInstruction,
    //    NopInstruction,
    //    NotInstruction,
    //    OrInstruction,
    //    OverInstruction,
    //    PopInstruction,
    //    Pop2Instruction,
    //    RemInstruction,
    //    RemUnInstruction,
    //    RetInstruction,
    //    RotInstruction,
    //    ShlInstruction,
    //    ShrInstruction,
    //    ShrUnInstruction,
    //    StelemInstruction,
    //    Stloc0Instruction,
    //    Stloc1Instruction,
    //    Stloc2Instruction,
    //    Stloc3Instruction,
    //    SubInstruction,
    //    SwapInstruction,
    //    TuckInstruction,
    //    XorInstruction,

    //    LdargInstruction,
    //    LdargaInstruction,
    //    LdlocInstruction,
    //    LdlocaInstruction,
    //    StargInstruction,
    //    StlocInstruction,

    //    CalliInstruction,

    //    CallInstruction,
    //    LdftnInstruction,

    //    BeqInstruction,
    //    BeqUnInstruction,
    //    BgeInstruction,
    //    BgeUnInstruction,
    //    BgtInstruction,
    //    BgtUnInstruction,
    //    BleInstruction,
    //    BleUnInstruction,
    //    BltInstruction,
    //    BltUnInstruction,
    //    BneInstruction,
    //    BneUnInstruction,
    //    BrInstruction,
    //    BrfalseInstruction,
    //    BrinstInstruction,
    //    BrnullInstruction,
    //    BrtrueInstruction,
    //    BrzeroInstruction,

    //    LdcF32Instruction,
    //    LdcF64Instruction,
    //    LdcI32Instruction,
    //    LdcI64Instruction,

    //    LdnullInstruction,
    //    NewarrInstruction,
    //    NewobjInstruction,

    //    LdfldInstruction,
    //    LdfldaInstruction,
    //    LdsfldInstruction,
    //    LdsfldaInstruction,
    //    StfldInstruction,
    //    StsfldInstruction,

    //    EndOfFileToken,

    //    BadToken,

    //    IdentifierToken,
    //    StringLiteralToken,
    //    CharacterLiteralToken,
    //    I32LiteralToken,
    //}
}
